topic:
  name: ${KAFKA_FUNC_TOPIC:topic}
  partitions-num: 1
  replication-factor: 1

server:
  port: 9080

spring:
  # banner
  banner:
    location: classpath:banner/banner.txt
  kafka:
    bootstrap-servers:
      - ${KAFKA_URI_PLAINTEXT:http://localhost:9192}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:8083}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
    template:
      default-topic:

logging:
  level:
    root: info

default:
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:rock}
    user: system
    password: system
  check:
    delay: 1
    retry: 30

modules:
  sql:
    connect :
      function: io.rocktest.modules.Sql.connect
    request :
      function: io.rocktest.modules.Sql.request

  http:
    get:
      function: io.rocktest.modules.Http.get
    delete :
      function: io.rocktest.modules.Http.delete
    post :
      function: io.rocktest.modules.Http.post
    put :
      function: io.rocktest.modules.Http.put
    mock :
      function: io.rocktest.modules.Http.mock

  json :
    parse :
      function: io.rocktest.modules.JSon.parse
      result: result
      extension: path
      params:
        1: json

  date:
    now:
      function: io.rocktest.modules.Date.now
      result: result

    minus :
      function: io.rocktest.modules.Date.minus
      result: result
      params:
        1: date
        2: years
        3: months
        4: days

  web:
    get:
      function: io.rocktest.modules.Web.get
    quit:
      function: io.rocktest.modules.Web.quit
    click:
      function: io.rocktest.modules.Web.click
    window:
      function: io.rocktest.modules.Web.window
      result: result
    switch:
      function: io.rocktest.modules.Web.switchTo
    newwindow:
      function: io.rocktest.modules.Web.newWindow
      result: result
    sendkeys:
      function: io.rocktest.modules.Web.sendKeys
    clear:
      function: io.rocktest.modules.Web.clear
    submit:
      function: io.rocktest.modules.Web.submit
    css:
      function: io.rocktest.modules.Web.css
      result: result
      extension: name
    text:
      function: io.rocktest.modules.Web.text
      result: result
    attribute:
      function: io.rocktest.modules.Web.attribute
      result: result
      extension: name
    title:
      function: io.rocktest.modules.Web.title
      result: result
    url:
      function: io.rocktest.modules.Web.url
      result: result
    tag:
      function: io.rocktest.modules.Web.tag
      result: result
    count:
      function: io.rocktest.modules.Web.count
      result: result

  regex:
    match:
      function: io.rocktest.modules.Regex.match
      result: result
      extension: group
      params:
        1: pattern
        2: string

  assert:
    equals:
      function: io.rocktest.modules.Assert.equals
    match:
      function: io.rocktest.modules.Assert.match
